// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Posts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Lista de Posts --><section aria-labelledby=\"posts\"><h2 id=\"posts\">Posts Recentes</h2><article><h3><a href=\"/post/1\">Título do Post 1</a></h3><p>Resumo do post 1. Este é um pequeno trecho do conteúdo...</p><a href=\"/post/1\" class=\"read-more\" aria-label=\"Leia mais sobre Título do Post 1\">Leia mais</a></article><article><h3><a href=\"/post/2\">Título do Post 2</a></h3><p>Resumo do post 2. Este é um pequeno trecho do conteúdo...</p><a href=\"/post/2\" class=\"read-more\" aria-label=\"Leia mais sobre Título do Post 2\">Leia mais</a></article><!-- Adicione mais artigos conforme necessário --></section><!-- Botão para criar novo post --><button hx-put=\"/novo\" class=\"btn btn-primary\">Novo Post</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
